# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:
  postgres:
    image: postgres:17beta2
    environment:
      POSTGRES_DB: primary
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  backup:
    build:
      context: .
      args:
        ALPINE_VERSION: '3.16'
    environment:
      SCHEDULE: '@weekly'     # optional
      BACKUP_KEEP_DAYS: 7     # optional
      PASSPHRASE: passphrase  # optional
      S3_REGION:
      S3_ACCESS_KEY_ID:
      S3_SECRET_ACCESS_KEY:
      S3_BUCKET:
      POSTGRES_DB: primary
      POSTGRES_DB_URL: postgres://user:password@postgres:5432/primary
